export const ROLES = ['admin', 'sales'];

export const REGISTRATION_STATUSES = ['ACTIVE', 'COMPLETED', 'EXPIRED'];

export const PAYMENT_MODES = ['CASH', 'CHEQUE', 'UPI', 'NEFT', 'RTGS', 'IMPS'];

export const AUDIT_ACTIONS = [
  'SCHEME_CREATED',
  'SCHEME_UPDATED',
  'SCHEME_DELETED',
  'REGISTRATION_CREATED',
  'VALIDATION_EMAIL_SENT',
  'REGISTRATION_COMPLETED',
  'REGISTRATION_EXPIRED',
  'DISPATCH_ADDED',
  'PRINT_GENERATED',
  'USER_CREATED',
  'USER_UPDATED',
  'SETTINGS_UPDATED',
];
