export const ROLES = ['admin', 'sales'];

// Login protections
export const MAX_LOGIN_ATTEMPTS = 5;
export const LOGIN_LOCK_MINUTES = 15;
export const LOGIN_RATE_WINDOW_MS = 15 * 60 * 1000;
export const LOGIN_RATE_MAX = 15;

export const REGISTRATION_STATUSES = ['ACTIVE', 'COMPLETED', 'EXPIRED'];

export const PAYMENT_MODES = ['CASH', 'CHEQUE', 'UPI', 'NEFT', 'RTGS', 'IMPS'];

export const AUDIT_ACTIONS = [
  'SCHEME_CREATED',
  'SCHEME_UPDATED',
  'SCHEME_DELETED',
  'REGISTRATION_CREATED',
  'SCREENSHOT_UPDATED',
  'VALIDATION_EMAIL_SENT',
  'REGISTRATION_COMPLETED',
  'REGISTRATION_EXPIRED',
  'DISPATCH_ADDED',
  'PRINT_GENERATED',
  'USER_CREATED',
  'USER_UPDATED',
  'SETTINGS_UPDATED',
];
